### ISSUE TITLE
Make error in Ubuntu 22 Digital Ocean

### ISSUE THREAD

**Issue by jjsainzc** [skiphansen/thelinkbox#5]
/usr/bin/ld: ../src/libtbd.a(conference.o):/root/thelinkbox/src/conference.c:889: multiple definition of `bLogCmd'; nodes.o:/root/thelinkbox/linkbox/nodes.cpp:352: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:453: tlb] Error 1
make[2]: Leaving directory '/root/thelinkbox/linkbox'
make[1]: *** [Makefile:477: all-recursive] Error 1
make[1]: Leaving directory '/root/thelinkbox'
make: *** [Makefile:397: all] Error 2

**Comment by skiphansen** [comment]
@jjsainzc Thanks for the report.  I don't have access to a Ubuntu 22 to test on but I think I've probably fixed the issue.  Prior to the fix it compiled with only warnings on Ubuntu 20.04 & Gcc 9.4.0.  Gcc gets pickier and pickier every release (which isn't necessarily a bad thing), when this code was originally written 20 years ago things were a bit different.

Please update and let me know if the issue is resolved.

**Comment by skiphansen** [comment]
Builds successfully on Ubuntu 22.04.1 / gcc 11.3.0.
